### ISSUE TITLE
zombie simulation fails when using IntelMPI

### ISSUE THREAD

**Issue by mkiernan** [Repast/repast.hpc#2]
When running Intel MPI 2018.4 with repast 2.3, & boost_mpi 1.69, the zombie simulation fails consistently with the same error. 

The rumor demo on the other hand, works fine on the same system. 

Any idea how to work resolve this ?

(gdb) run config.props model.props
Starting program: /opt/repast_hpc/bin/zombie/./zombie_model config.props model.props
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffeb020700 (LWP 31483)]
 Starting...
17.02.2019 08:44:12 [0] INFO root TICK BEGINS: 1

zombie_model: /usr/local/include/boost/mpi/communicator.hpp:1951: boost::mpi::request boost::mpi::communicator::irecv_impl(int, int, T&, mpl_::false_) const [with T = repast::SyncStatus_Packet<AgentPackage>; mpl_::false_ = mpl_::bool_<false>]: Assertion `_check_result == 0' failed.

**Comment by ncollier** [comment]
No doubt you've tried this, but I'm assuming you get the error with `mpirun -n 4 ./zombie_model config.props model.props` too? I ask because the Zombie model will segfault if run on a single process as in your gdb example. 

We have run the Zombie model on an earlier version, but still 2018, of Intel's MPI without issue, so I don't think it is related to that.
